steps:
  # build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/hike-review/github.com/hike-review/mysql:$COMMIT_SHA', '.']
    
  # push image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/hike-review/github.com/hike-review/mysql:$COMMIT_SHA']
    
  # deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'mysql'
      - '--image=gcr.io/hike-review/github.com/hike-review/mysql:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--service-account=641428707740-compute@developer.gserviceaccount.com'
      - '--set-secrets=MYSQL_PASSWORD=secretName=password'
    
images:
  - 'gcr.io/hike-review/github.com/hike-review/mysql:$COMMIT_SHA'